OpenRA/raclassic

mods/raclassic/rules/structures.yaml
Also removed some lingering stuff from openra's ra mod
=> Adjust structure cost, health, power consumption

mods/raclassic/rules/civilian.yaml
∙Replaced ExternalCapturable with Capturable.
∙Adjusted health & vision radius.
∙Adjusted power requirements for FCOM & BIO.
∙Changed the name of MISS & BIO.
∙Disabled Gap Generated vision differences.
=> updated fcom,miss,hosp,bio

mods/raclassic/rules/structures.yaml
`FallbackRange:` is something to do with Garrison logic, it is not required.
=> Pillbox stuff

mods/raclassic/rules/structures.yaml, mods/raclassic/rules/vehicles.yaml
One was my error, other is @FrameLimiter 's.
=> Fix crashes

mods/raclassic/rules/aircraft.yaml
Also adjusted TRAN cargo capacity.
=> Adjusted cost, hp, turn speeds. Removed vision & contrails

mods/raclassic/rules/world.yaml
Crates now appear normally, like in original or in other mods.
=> Remove crate dropping badger

mods/raclassic/rules/world.yaml
Adds starting units from original 0 to 12. Looks like 6 was default in original so i set default to 6 here.
=> Add original starting units

mods/raclassic/rules/infantry.yaml
In addition also:
∙Made the shock trooper uncrushable.
∙Replaced the thief's obsolete "InfiltrateTypes" with "Types".
∙Added build-able prerequisites for the thief.
=> Adjusted cost, hp, and vision.

mods/raclassic/chrome/ingame-player.yaml, mods/raclassic/rules/fakes.yaml, mods/raclassic/rules/player.yaml, mods/raclassic/rules/structures.yaml
=> Remove defence tab and reorder structures tab

mods/raclassic/rules/fakes.yaml
=> Add fake building's tech levels.

mods/raclassic/rules/structures.yaml
Button no longer does anything.
=> Remove CanPowerDown: from all structures

mods/raclassic/sequences/misc.yaml, mods/raclassic/sequences/structures.yaml
Missed this when doing #17, found with debug.log.
=> Remove unused minibib sequences

mods/raclassic/rules/defaults.yaml, mods/raclassic/rules/fakes.yaml
Corrects health, armor, cost, power consumption, and also capturable. Removes the explode logic the ra mod uses.
=> Fake building adjustments

mods/raclassic/rules/misc.yaml, mods/raclassic/rules/structures.yaml
SWs from crates now charge, they are not instant.
Units from crates depend on side, sovs can't get allied units and vice versa.
Added some more infantry crate types, as i can see from my tests.
IC and Powerup crates now effect units in 3 cell range.
Also fixed nuke timer to 13 mins.
=> Some more changes to crates

mods/raclassic/maps/shellmap/map.yaml, mods/raclassic/maps/shellmap/rules.yaml, mods/raclassic/maps/shellmap/shellmap.lua
=> Change crate artwork to original ones

mods/raclassic/weapons/ballistics.yaml
∙Also removed the inaccuracy from the 155mm.
=> Removed contrails from 155mm/8inch.

mods/raclassic/rules/aircraft.yaml, mods/raclassic/weapons/missiles.yaml, mods/raclassic/weapons/smallcaliber.yaml
Makes smallcalibers and missiles match the original, at least the damage, reload, range and versus values. Also ammo for aircraft.
=> More weapon changes to match original

mods/raclassic/rules/infantry.yaml
She was shown when you only have kennel.
=> Fix Tanya Prerequisite

mods/raclassic/rules/infantry.yaml
Called "GuardRange" in original game.
https://github.com/OpenRA/raclassic/blob/master/ref/Rules.ini#L438
=> AutoTarget ScanRadius updated for dog & e3

mods/raclassic/rules/defaults.yaml, mods/raclassic/rules/misc.yaml, mods/raclassic/rules/vehicles.yaml, mods/raclassic/weapons/explosions.yaml
Fixes #49. 
Explosion anims and sounds are still not matching the original.
I'm also not sure if AP Mine's damage vs vehicles is correct, but it looks like it.
=> Make Minelayers work as in original

mods/raclassic/chrome/ingame-player.yaml, mods/raclassic/hotkeys.yaml, mods/raclassic/rules/ai.yaml, mods/raclassic/rules/civilian.yaml, mods/raclassic/rules/defaults.yaml, mods/raclassic/rules/fakes.yaml, mods/raclassic/rules/infantry.yaml, mods/raclassic/rules/player.yaml, mods/raclassic/rules/ships.yaml, mods/raclassic/rules/structures.yaml, mods/raclassic/rules/vehicles.yaml, mods/raclassic/rules/world.yaml, mods/raclassic/tilesets/desert.yaml
All the changes should be noted in the commit messages or decs.
=> More release changes

make.ps1
Applying https://github.com/OpenRA/OpenRAModSDK/pull/68 to here.
=> Fix downloading the engine on Windows

mods/raclassic/rules/civilian.yaml, mods/raclassic/sequences/structures.yaml
Hospital was crashing the game as it had WithBuildingBib, but no bib
sequence definition. Looks like these had bibs like this in the
original.
=> Give Bio Lab and Hospital proper bibs.

mods/raclassic/rules/aircraft.yaml
https://github.com/OpenRA/raclassic/blob/master/ref/Rules.ini#L1149
=> Fix Yak's cost

mods/raclassic/rules/campaign-rules.yaml
DefaultCashLocked has been changed to DefaultCashDropdownLocked.
https://github.com/OpenRA/OpenRA/wiki/Traits#playerresources
=> PlayerResources DefaultCashLocked name updated

mods/raclassic/rules/player.yaml, mods/raclassic/rules/world.yaml
I missed this while updating the mod to new version.
=> Fix order of new Seperate Team Spawns checkbox

mods/raclassic/rules/aircraft.yaml
https://github.com/OpenRA/raclassic/blob/master/ref/Rules.ini#L46
0.04 Mins = 2,4 Sec = 60 Ticks.
=> Change aircraft reload delays to match original

mods/raclassic/rules/aircraft.yaml, mods/raclassic/weapons/smallcaliber.yaml
=> Add Yak Strafing

mods/raclassic/rules/vehicles.yaml
=> Remove range limit from chrono tank

mods/raclassic/rules/vehicles.yaml
=> Increase Chrono Tank chrono reload delay

mods/raclassic/weapons/other.yaml
FireballLauncher [range=4](https://github.com/OpenRA/raclassic/blob/e19a38b4e90edde9a03ae5c169b267f2c9475170/ref/Rules.ini#L2143)
Fire warhead [spread=8](https://github.com/OpenRA/raclassic/blob/e19a38b4e90edde9a03ae5c169b267f2c9475170/ref/Rules.ini#L2692)
=> Adjust FireWeapon range & spread

mods/raclassic/rules/vehicles.yaml
[NoMovingFire=yes](https://github.com/OpenRA/raclassic/blob/c94e8019df2975f0c2448070597e5e572bf719a9/ref/aftrmath.ini#L75)
=> Remove move-while-firing from TTNK

mods/raclassic/rules/country-duplicates.yaml, mods/raclassic/rules/ships.yaml
https://github.com/OpenRA/raclassic/blob/master/ref/Rules.ini#L719
=> Remove radar requirement from destroyer.

mods/raclassic/rules/defaults.yaml, mods/raclassic/rules/player.yaml, mods/raclassic/rules/structures.yaml, mods/raclassic/rules/world.yaml
Disabled by default of course but this was in the ToDo so i decided to add it.
=> Add Limit Build Area Checkbox

mods/raclassic/rules/structures.yaml, mods/raclassic/weapons/explosions.yaml, mods/raclassic/weapons/superweapons.yaml
It is now less powerful and pretty useless as in original.
Considering how unpowerful the SWs was in original game, i wanna add a limit sws checkbox (enabled by default of course). I had such option on Generals Alpha.
=> Adjust nuke weapon.

mods/raclassic/rules/country-duplicates.yaml, mods/raclassic/rules/fakes.yaml, mods/raclassic/rules/infantry.yaml, mods/raclassic/rules/misc.yaml, mods/raclassic/rules/player.yaml, mods/raclassic/rules/ships.yaml, mods/raclassic/rules/structures.yaml, mods/raclassic/rules/vehicles.yaml
Disabled by default, even tho was the case in original game because it is mostly a bad thing, but i'm still adding if someone wants it. Also this is pretty hacky.
=> Add Sticky Tech checkbox

mods/raclassic/rules/defaults.yaml, mods/raclassic/rules/infantry.yaml, mods/raclassic/rules/player.yaml
=> Add Auto-Scatter checkox

mods/raclassic/weapons/ballistics.yaml, mods/raclassic/weapons/missiles.yaml
Decreases 2/3TNK damage from 40 to 30.
Increases 3TNK Burst Delay to 5.
Increases 4TNK Cannon Projectile speed to 600 from 450.
Increases MiG projectile speed to 450 from 375.
Increases Turret projectile speed from 600 to 750.
=> Some weapon fixes.

mods/raclassic/rules/defaults.yaml, mods/raclassic/rules/infantry.yaml, mods/raclassic/rules/player.yaml, mods/raclassic/rules/structures.yaml, mods/raclassic/rules/vehicles.yaml, mods/raclassic/weapons/smallcaliber.yaml
=> Add Blockable Bullets checkbox

mod.config, mods/raclassic/mod.yaml
No further changes seem to be required since this is just a bugfix version.
=> Update engine version

mods/raclassic/mod.yaml
Still kept some of the messages from OpenRA RA mod. But mostly new custom ones.
=> Give mod its own load-screen messages.

mods/raclassic/rules/ai.yaml
Merges shared modules into 1 trait.
Makes AI able to build Tanya or Volkov.
=> AI.yaml adjustments

mods/raclassic/rules/ships.yaml
=> Fix Turn Speed of Cruiser.

mod.config, mods/raclassic/mod.yaml
No additional changes seem to be required.
=> Update engine to new release.

OpenRA.Mods.Raclassic/OpenRA.Mods.Raclassic.csproj, OpenRA.Mods.Raclassic/Widgets/Logic/TemplateMenuLogic.cs, Raclassic.sln, mod.config, mods/raclassic/mod.yaml
Just copy pasted the example dll. The SDK updates in the previous PR probably reverted the removal of some stuff that was about the DLL and i decided that actually adding the DLL would be easier than finding what was changed. Also should make further SDK updates easier. And we may need a custom DLL eventually.
=> Give the mod a custom DLL.

mod.config, mods/raclassic/mod.yaml, packaging/linux/buildpackage.sh
Fixes #177. No additional changes seem to be necessary.
=> Update engine version to playtest-20200118.

mod.config, mods/raclassic/mod.yaml
No additional changes seem to be necessary.
=> Update engine version to release-20200202

mods/raclassic/rules/infantry.yaml
=> Fix Volkov crashing the game while playing idle anim.

launch-dedicated.cmd, launch-dedicated.sh, mod.config, mods/raclassic/mod.yaml, mods/raclassic/rules/structures.yaml, packaging/windows/buildpackage.nsi
=> Update engine version to playtest-202020418.

mods/raclassic/rules/duplicates.yaml, mods/raclassic/rules/structures.yaml
I dunno why i implemented the IC like that at the first place and not removed the duplicate BRIK along with the rest of Russian and Turkish stuff.
=> Remove 2 unnecessary duplicates.

packaging/linux/buildpackage.sh
Didn't notice that it failed while posting and PChote noticed and messaged while i was in bed, so fixing it now.
=> Fix linux packaging.

mod.config, mods/raclassic/mod.yaml
No additional changes seem to be required.
=> Update engine version to playtest-20210131.

mods/raclassic/chrome/ingame-player.yaml
Decided to play a test game before doing a released. Game crashed when i captured an Allied ConYard as Soviets. Looks like scrollbar definitions was wrong.
=> Fix crash when getting both ConYards.

mods/raclassic/rules/defaults.yaml
Yeah, i complately forgot this needed yaml changes even tho i did it for RV few hours ago.
=> Make Handicap option actually work.

launch-dedicated.sh, mod.config, mods/raclassic/chrome.yaml, mods/raclassic/mod.yaml
It is not out yet but looks like release is already generated, we are just waiting for website stuff so decided to handle this. Applied the fix from https://github.com/OpenRA/OpenRAModSDK/pull/174 and another small fix that shouldn't effect here since we don't have missions to play videos on.
=> Update engine version to release-20210321.
