- mods/raclassic/rules/defaults.yaml
- mods/raclassic/rules/infantry.yaml
- mods/raclassic/rules/structures.yaml
- mods/raclassic/rules/vehicles.yaml
- mods/raclassic/sequences/vehicles.yaml
Also complately removed Mobile Flak and made Supply Truck unbuildable.
> Disable aftermath units

- mods/raclassic/rules/ships.yaml
Disabled the MSUB as it was an aftermath unit.
> Adjusted cost, hp, turn speed, and vision

- mods/raclassic/rules/player.yaml
Looks like original game had from 0 to 10000, maybe because no-base games was a thing. But i don't think anything below 2500 is necessary as PP + REF costs 2300.
That much selection looks a bit wierd with dropdown menu, i tryed adding a scroll bar to it but couldn't manage, i think editing C# code is required for that.
> Add cash options from 2500 to 10000

- mods/raclassic/rules/misc.yaml
- mods/raclassic/rules/structures.yaml
Looks like Sellable don't have a tag to set those, so it has so stay for it.
> Remove Cash Ticks from Refinery and Crates

- mods/raclassic/rules/infantry.yaml
I kept him unbuildable as it didn't work, but looks like FrameLimiter added it.
> Make Thief buildable

- mods/raclassic/rules/defaults.yaml
- mods/raclassic/rules/structures.yaml
Also removes power requirements from SWs, which from my tests it looks like original didn't have.
> Remove low power overlay

- mods/raclassic/rules/world.yaml
Occurs because SpawnMPUnits adds `+1` to `InnerSupportRadius` when finding an annulus to spawn units in, which won't work.
> Fix crash with 1 mp starting unit

- mods/raclassic/rules/structures.yaml
It didn't require power in original.
> Remove power requirements from SAM Site

- mods/raclassic/rules/misc.yaml
- mods/raclassic/weapons/other.yaml
Except ICBM/Nuke, NukePower doesn't work on a proxy actor.
I'm not sure how TimeQuake worked in original, it currently deals 33% damage to all Buildings and Vehicles.
Also Parabomb looks a bit too powerful. looks like we haven't adjusted its values yet.
> Added original crate powers

- mods/raclassic/rules/defaults.yaml
- mods/raclassic/rules/structures.yaml
- mods/raclassic/weapons/ballistics.yaml
- mods/raclassic/weapons/explosions.yaml
- mods/raclassic/weapons/missiles.yaml
It was called `building` appearantly in OpenRA, i didn't change the name.
This makes buildings only use this anim on death, also changes Artillery, V2, Crusier and Missile Sub's weapons to use it.
> Changed some weapons to use large explosion as in original

- mods/raclassic/rules/aircraft.yaml
- mods/raclassic/rules/campaign-palettes.yaml
- mods/raclassic/rules/defaults.yaml
- mods/raclassic/rules/infantry.yaml
- mods/raclassic/rules/palettes.yaml
- mods/raclassic/rules/ships.yaml
- mods/raclassic/rules/structures.yaml
- mods/raclassic/rules/vehicles.yaml
- mods/raclassic/weapons/ballistics.yaml
- mods/raclassic/weapons/missiles.yaml
- mods/raclassic/weapons/superweapons.yaml
I have done some stuff while i was alone with no internet:
- Spy disguise logic removed. Currently no units but dogs AutoTarget them. You can (and AI do too) still manually target them. Still not the same as original, but i think closer.
- Spy weapon is removed.
- Removed contrails from missiles.
- Adjusted some values for Aftermath units. Removed Missile Sub AA.
- Units now leave War Factory directly to south as in original, instead of with a wierd angle.
> Some mostly small adjustments

- mods/raclassic/rules/defaults.yaml
- mods/raclassic/rules/vehicles.yaml
Tracked values are set by Tracked=yes tag in original code.
I made crushing according to this test i made, i fenced some enemy spies in and tested what can crush them.
It appears that everthing except demo/supply truck, ranger and arty can crush.
Also adjusted terrain modifiers according to original game, for Infantry too.
> Adjust Tracked and Crusher status of units

- mods/raclassic/weapons/other.yaml
Speed = 100 means instant hit original. Some other weapons also use it, but i'll edit them with another PR.
Similarly Spread = 0 means only damage the target, which is what our TargetDamage Warhead does. No need to mess with too small Spread values.
Without `TargetActorCenter: true` medic didn't work, while mechanic does, not sure what exactly is the reason. Also looks like TS Mod also uses these for medic: https://github.com/OpenRA/OpenRA/blob/bleed/mods/ts/weapons/healweapons.yaml
> Make Heal weapons use InstantHit Proj and TargetDamage Warhead

- mods/raclassic/rules/structures.yaml
#56 updated the duration of the iron curtain instead of charge time, this restores the 45 seconds duration and sets 5 minute cooldown
> Iron Curtain charge time/duration fix

- mods/raclassic/rules/vehicles.yaml
The phase transport could not be repaired by mechanics while cloaked in the original game.
> Removed MECH repair for STNK while cloaked

- mods/raclassic/audio/voices.yaml
- mods/raclassic/metrics.yaml
- mods/raclassic/mod.yaml
- mods/raclassic/rules/ai.yaml
- mods/raclassic/rules/aircraft.yaml
- mods/raclassic/rules/country-duplicates.yaml
- mods/raclassic/rules/defaults.yaml
- mods/raclassic/rules/fakes.yaml
- mods/raclassic/rules/infantry.yaml
- mods/raclassic/rules/misc.yaml
- mods/raclassic/rules/player.yaml
- mods/raclassic/rules/ships.yaml
- mods/raclassic/rules/structures.yaml
- mods/raclassic/rules/vehicles.yaml
- mods/raclassic/rules/world.yaml
- mods/raclassic/weapons/ballistics.yaml
- mods/raclassic/weapons/missiles.yaml
This differs a lot from original. Because Countries in original game was a buggy mess.
- England's Armor and France's ROF bonus was buggy in original, making them weak/fire slower. They properly get their bonuses here.
- Russia's cost bonus has a wierd calculation error. Making stuff above $300 original cost $1-4 cheaper then actual 10%. I did NOT fix that. Because i think wierd costs of Russia gives a classic feeling and is too low to do a real difference. But this cost bonus was also effecting build time in original and was most likely a bug, becuase there is [a seperate ini entry for BuildTime](https://github.com/OpenRA/raclassic/blob/master/ref/Rules.ini#L313), not sure if works or not, no vanilla faction uses it.
- Ukraine's speed bonus in original only effected ground units, it …
> Add Countries

- mods/raclassic/rules/aircraft.yaml
- mods/raclassic/rules/defaults.yaml
- mods/raclassic/rules/infantry.yaml
- mods/raclassic/rules/ships.yaml
- mods/raclassic/rules/vehicles.yaml
I have no idea about the original calculations, i just wrote x10 of the original value and also put a 125% Modifier on all units because it normally felt low and i wanted to keep the actual speed values resemble the original. I did simiar thing on Generals Alpha too to use the original speed values.
This doesn't match the original 100% tho, it should be close enough and at least make the relative speeds to other units same as original.
> Change movement speeds to match original

- mods/raclassic/rules/aircraft.yaml
- mods/raclassic/rules/defaults.yaml
- mods/raclassic/rules/structures.yaml
Aircraft don't take off on creation/rearm.
Helipad can build out of map if all the helipads are occupied.
All the helis can land on ground.
You can sell Aircraft on HPAD/AFLD properly.
Aircraft no longer apply docked condition while flying over FIX.
Airfield and Helipad no longer has Rally Point, as now new aircraft is docked, also ProductionFromMapEdge don't work properly with it.
> Changes to aircraft to be more like original

- mods/raclassic/weapons/ballistics.yaml
- mods/raclassic/weapons/missiles.yaml
- mods/raclassic/weapons/other.yaml
Some units (Artillery, Grenadier, Cruiser) feel wrong. I feel like in the original distance actually effects the projectile speed. Because i tested with Cruiser and make it fire really close, projectile is slow, when firing far it is faster.
Arty and Gren are meh. Cruiser feels really wrong, tho lets keep it like that for now, it was pretty OP in original.
> Adjust projectile speeds

- mods/raclassic/rules/player.yaml
Not sure if this is correct, but https://www.moddb.com/mods/the-dawn-of-the-tiberium-age/images/multiple-factory-bonus#imagebox says this is correct for TS, so i guess it would be same in RA.
> Adjust BuildTimeSpeedReduction to better match the original

- mods/raclassic/rules/aircraft.yaml
- mods/raclassic/rules/defaults.yaml
They are removed in upsteram too.
Tho, i just noticed we should probably remove the faction duplicates too, as i removed D2k starport units at upstream.
> Remove aircraft Husks and AttackBombers from map editor

- mods/raclassic/rules/country-duplicates.yaml
- mods/raclassic/rules/structures.yaml
Other mission ruleset dupes has changes other than cost, so one or other being the preplaced one may matter, for Country Dupes and Mission Concrete Wall it doesn't.
> Remove Country Duplicates and Mission C. Wall from Map Editor

- mods/raclassic/rules/infantry.yaml
- mods/raclassic/rules/player.yaml
Enabled by default, disabling makes it so 1 engi can capture a building.
> Add Multi-Engineer checkbox

- mods/raclassic/rules/ai.yaml
- mods/raclassic/rules/misc.yaml
This used to crash the game so i couldn't add it. It now works on playtest-20200303.
> Add A-Bomb Crates.

- mods/raclassic/chrome/ingame-player.yaml
This button is removed upstream, chrome.yaml seem to have been updated for this change but not ingame-player.yaml so it was crashing saying `debug` wasn't found under `order-icons`.
> Fix Debug Menu crash.
